include: package:all_lint_rules_community/all.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"
    - "**/generated_plugin_registrant.dart"

  errors:
    fixme: ignore
    hack: ignore
    todo: ignore
    included_file_warning: ignore
    invalid_annotation_target: ignore

  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    always_put_control_body_on_new_line: false
    always_put_required_named_parameters_first: false
    always_specify_types: false
    always_use_package_imports: false
    avoid_annotating_with_dynamic: false
    avoid_as: false
    avoid_catches_without_on_clauses: false
    cascade_invocations: false
    depend_on_referenced_packages: false
    diagnostic_describe_all_properties: false
    flutter_style_todos: false
    no_default_cases: false
    prefer_double_quotes: false
    prefer_expression_function_bodies: false
    prefer_final_parameters: false
    public_member_api_docs: false
    unnecessary_final: false
