name: theme
description: Theme for fl_template
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.2.0

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^3.0.1

dev_dependencies:
  all_lint_rules_community: ^0.0.14
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - google_fonts/
