name: adapter
description: Adapter for fl_template
publish_to: none

version: 0.1.0

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^4.0.6
  intl: ^0.17.0
  logger: ^1.1.0
  model:
    path: ../model

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4
  http_mock_adapter: ^0.3.2
  test: ^1.19.5
