name: adapter
description: Adapter for fl_template
publish_to: none

version: 0.4.0

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.4.1
  intl: ^0.18.1
  logger: ^2.1.0
  model:
    path: ../model

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  http_mock_adapter: ^0.6.1
  test: ^1.24.9
