name: adapter
description: Adapter for fl_template
publish_to: none

version: 0.3.0

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.0.2
  intl: ^0.18.0
  logger: ^1.3.0
  model:
    path: ../model

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  http_mock_adapter: ^0.4.2
  test: ^1.19.5
