name: adapter
description: Adapter for fl_template
publish_to: none

version: 0.2.0

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^4.0.6
  intl: ^0.17.0
  logger: ^1.1.0
  model:
    path: ../model

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  http_mock_adapter: ^0.3.3
  test: ^1.19.5
