name: adapter
description: Adapter for fl_template
publish_to: none

version: 0.4.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.3.2
  intl: ^0.18.0
  logger: ^2.0.1
  model:
    path: ../model

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2
  http_mock_adapter: ^0.4.4
  test: ^1.24.1
