include: package:flutter_lints/flutter.yaml
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    fixme: ignore
    hack: ignore
    todo: ignore
    invalid_annotation_target: ignore
linter:
  rules:
    prefer_const_constructors: false
    prefer_final_locals: true
    prefer_relative_imports: true
    prefer_single_quotes: true
    public_member_api_docs: false
    require_trailing_commas: true
