name: model
description: Model for fl_template
publish_to: none

version: 0.3.0

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  freezed: ^2.3.3
  json_serializable: ^6.6.2
  test: ^1.21.7
