name: model
description: Model for fl_template
publish_to: none

version: 0.4.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.10
  flutter_lints: ^4.0.0
  freezed: ^2.5.3
  json_serializable: ^6.8.0
  test: ^1.25.2
