name: model
description: Model for fl_template
publish_to: none

version: 0.4.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.2
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  test: ^1.24.4
