name: model
description: Model for fl_template
publish_to: none

version: 0.4.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.5
  flutter_lints: ^2.0.1
  freezed: ^2.3.5
  json_serializable: ^6.7.0
  test: ^1.24.3
