name: model
description: Model for fl_template
publish_to: none

version: 0.1.0

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  freezed_annotation: ^2.0.1
  json_annotation: ^4.4.0

dev_dependencies:
  analyzer: 3.4.1 # specify analyzer version to avoid updating to 4.0.0
  build_runner: ^2.1.10
  flutter_lints: ^1.0.4
  freezed: ^2.0.2
  json_serializable: ^6.1.6
  test: ^1.20.1
