name: template
description: UI for fl_template
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.4.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  adapter:
    path: ../adapter
  animated_path: ^0.0.2
  animations: ^2.0.11
  basic_utils: ^5.6.1
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.8
  device_info_plus: ^10.1.0
  email_validator: ^2.1.17
  equatable: ^2.0.5
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_hooks: ^0.20.5
  flutter_secure_storage: ^9.2.1
  gap: ^3.0.1
  go_router: ^14.0.2
  golden_toolkit: ^0.15.0
  hooks_riverpod: ^2.5.1
  intl: ^0.19.0
  logger: ^2.3.0
  model:
    path: ../model
  package_info_plus: ^8.0.0
  rfw: ^1.0.26
  shared_preferences: ^2.2.3
  signals: ^5.2.1
  theme:
    path: ../theme
  url_launcher: ^6.2.6
  xterm: ^4.0.0

dev_dependencies:
  all_lint_rules_community: ^0.0.40
  build_runner: ^2.4.10
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4

# dependency_overrides:

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/config/
    - google_fonts/
