name: template
description: UI for fl_template
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.4.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  adapter:
    path: ../adapter
  animated_path: ^0.0.2
  animations: ^2.0.7
  basic_utils: ^5.5.4
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.5
  device_info_plus: 9.0.1
  email_validator: ^2.1.17
  equatable: ^2.0.5
  fl_chart: ^0.62.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_hooks: ^0.18.6
  flutter_secure_storage: ^8.0.0
  gap: ^3.0.0
  go_router: ^7.0.2
  golden_toolkit: ^0.15.0
  graphx: ^1.0.12
  hooks_riverpod: ^2.3.6
  intl: ^0.18.1
  logger: ^1.3.0
  model:
    path: ../model
  package_info_plus: 4.0.1
  shared_preferences: ^2.1.1
  theme:
    path: ../theme
  url_launcher: ^6.1.11

dev_dependencies:
  all_lint_rules_community: ^0.0.31
  build_runner: ^2.4.4
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  shaders:
    - shaders/worley.frag
  assets:
    - assets/config/
    - google_fonts/
