name: template
description: UI for fl_template
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.3.0

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  adapter:
    path: ../adapter
  animated_path: ^0.0.2
  animations: ^2.0.7
  basic_utils: ^5.4.2
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.5
  device_info_plus: ^8.0.0
  email_validator: ^2.1.17
  equatable: ^2.0.5
  fl_chart: ^0.55.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_hooks: ^0.18.5
  flutter_secure_storage: ^7.0.1
  gap: ^2.0.1
  go_router: ^6.0.1
  golden_toolkit: ^0.14.0
  google_maps_flutter: ^2.2.3
  hooks_riverpod: ^2.1.3
  intl: ^0.18.0
  logger: ^1.1.0
  model:
    path: ../model
  package_info_plus: ^3.0.2
  shared_preferences: ^2.0.17
  theme:
    path: ../theme
  url_launcher: ^6.1.8

dev_dependencies:
  all_lint_rules_community: ^0.0.21
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.11.0
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/config/
    - google_fonts/
