name: template
description: UI for fl_template
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.2.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  adapter:
    path: ../adapter
  animations: ^2.0.2
  basic_utils: ^4.2.2
  cached_network_image: ^3.2.1
  cupertino_icons: ^1.0.4
  device_info_plus: ^3.2.3
  email_validator: ^2.0.1
  equatable: ^2.0.3
  fl_chart: ^0.50.5
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_hooks: ^0.18.4
  flutter_secure_storage: ^5.0.2
  gap: ^2.0.0
  go_router: ^3.1.0
  golden_toolkit: ^0.13.0
  hooks_riverpod: ^2.0.0-dev.7
  intl: ^0.17.0
  logger: ^1.1.0
  model:
    path: ../model
  package_info_plus: ^1.4.2
  shared_preferences: ^2.0.12
  theme:
    path: ../theme
  url_launcher: ^6.1.0

dev_dependencies:
  all_lint_rules_community: ^0.0.9
  build_runner: ^2.1.11
  flutter_launcher_icons:
    git:
      url: https://github.com/RatakondalaArun/flutter_launcher_icons.git
      ref: fix/flutter-v2.8.0-support-321
  flutter_test:
    sdk: flutter
  mockito: ^5.0.16

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/config/
    - google_fonts/
