name: template
description: UI for fl_template
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.4.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  adapter:
    path: ../adapter
  animated_path: ^0.0.2
  animations: ^2.0.7
  basic_utils: ^5.6.0
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.5
  device_info_plus: 9.0.2
  email_validator: ^2.1.17
  equatable: ^2.0.5
  fl_chart: ^0.63.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_hooks: ^0.18.6
  flutter_secure_storage: ^8.0.0
  gap: ^3.0.1
  go_router: ^9.0.3
  golden_toolkit: ^0.15.0
  graphx:
    git:
      url: https://github.com/chunghha/graphx
      ref: http_v1
  hooks_riverpod: ^2.3.6
  intl: ^0.18.1
  logger: ^1.4.0
  model:
    path: ../model
  package_info_plus: 4.0.2
  shared_preferences: ^2.2.0
  theme:
    path: ../theme
  url_launcher: ^6.1.12

dev_dependencies:
  all_lint_rules_community: ^0.0.31
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2

dependency_overrides:
  http: 1.1.0

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  shaders:
    - shaders/worley.frag
  assets:
    - assets/config/
    - google_fonts/
